### ISSUE TITLE
Feature request and bug fix

### ISSUE THREAD

**Issue by xkasprx** [MarkisDev/discordoauth#14]
Bug fix:
the /includes/oauth-login-widget.php file needs to be changed on line 28
old
'redirect_uri' => site_url( rest_get_url_prefix() . '/discord/callback', 'http' )
new
'redirect_uri' => site_url( rest_get_url_prefix() . '/discord/callback', 'https' )

Feature request:
Add guilds.join option to make the application join the user to the guild

Persistent bug:
After manually applying the fix above, login and user creation was successful but it did not redirect afterwards back to the site, Just stopped at 

siteurl.com/wp-json/discord/callback?code=auth-token-here

had to be done by navigating to the site again.

**Comment by f-o** [comment]
I do not know where this code comes from, but it has nothing to do with this script.

Closing this issue.

**Comment by KyleFardy** [comment]
> Bug fix: the /includes/oauth-login-widget.php file needs to be changed on line 28 old 'redirect_uri' => site_url( rest_get_url_prefix() . '/discord/callback', 'http' ) new 'redirect_uri' => site_url( rest_get_url_prefix() . '/discord/callback', 'https' )
> 
> Feature request: Add guilds.join option to make the application join the user to the guild
> 
> Persistent bug: After manually applying the fix above, login and user creation was successful but it did not redirect afterwards back to the site, Just stopped at
> 
> siteurl.com/wp-json/discord/callback?code=auth-token-here
> 
> had to be done by navigating to the site again.

if you read through the code, you would see i added that a while back
