### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Stage4000** [MarkisDev/discordoauth#15]
Hey I wanted to take a moment to say you rock dude. This script was absolutely perfect for me. You did all of the heavy lifting and made it so updating the code for my own use was easy as could be. Thank you so much for this.

**Comment by MarkisDev** [comment]
Hey! Thank you so much for the positive feedback! 
Appreciate it, I'm glad I could help you out :D

**Comment by Stage4000** [comment]
Hey there, I've run into a bit of a snag here that I'm sure is my own doing. I can't seem to get this to give me a role. I edited the join guild function to add a role ID `$data = json_encode(array("access_token" => $_SESSION['access_token'], "roles" => 1054537933824217169));` but it never gives me the role.

Possible conflicts:
-I'm already a member of the server before the auth is performed, thus discord doesn't even bother.
-I have intents set, I'm using all scopes, the bot role is above the control role. I've done the basic troubleshooting but I'm coming up empty.

Thanks in advance for your help.
