### ISSUE TITLE
License

### ISSUE THREAD

**Issue by benthetechguy** [MarkisDev/discordoauth#16]
This is an awesome piece of code that made things a lot easier for my website. I saw the copyright header at the top of discord.php, and I was just wondering what license this work falls under.
If there is no license, someone can put your code in their website with this header removed, and you would not get credit for your work. On the other hand, legally, not having a license automatically puts your work as all rights reserved copyright, which means that anyone modifying and redistributing the code would be doing so illegally.
I assume this is not what you intend, so maybe it's a good idea to add a license to this project.

**Comment by ifly-leonard** [comment]
I second this! 👍

**Comment by MarkisDev** [comment]
Hey! Thank you so much for the positive comments, we'll add a license to this ASAP.

**Comment by benthetechguy** [comment]
Define ASAP

**Comment by MarkisDev** [comment]
It's been done :) 
Thanks @f-o !
