### ISSUE TITLE
Invalid Oauth2 redirect_uri

### ISSUE THREAD

**Issue by YungSamzy** [MarkisDev/discordoauth#6]
I might have messed something up, but I believe it should work... I am trying to integrate this into my website but I get "Invalid Oauth2 redirect_uri" from discord when it tries to redirect.. Any help?

**Comment by xkasprx** [comment]
@YungSamzy the /includes/oauth-login-widget.php file needs to be changed on line 28
old
            'redirect_uri' => site_url(  rest_get_url_prefix() . '/discord/callback', 'http' )
new
            'redirect_uri' => site_url(  rest_get_url_prefix() . '/discord/callback', 'https' )
